# Generated by Django 5.2 on 2026-03-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='identificationNumber',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoiceNumber', models.IntegerField(unique=True)),
                ('issued', models.DateField()),
                ('dueDate', models.DateField()),
                ('product', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField()),
                ('vat', models.IntegerField()),
                ('note', models.CharField()),
                ('hidden', models.BooleanField(db_index=True, default=False)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyed_invoices', to='invoices.person')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selled_invoices', to='invoices.person')),
            ],
        ),
    ]
