# Generated by Django 5.2 on 2026-03-31 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_person_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_of_invoices', to='invoices.person'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='note',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_of_invoices', to='invoices.person'),
        ),
    ]
