# Generated by Django 5.2 on 2026-04-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_buyer_alter_invoice_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='hidden',
        ),
    ]
